package sql

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/schema-export/schema-export/internal/exporter"
	"github.com/schema-export/schema-export/internal/model"
)

// Exporter SQL DDL 导出器
type Exporter struct {
	dialect Dialect
}

// NewExporter 创建 SQL 导出器
func NewExporter() *Exporter {
	return &Exporter{
		dialect: &GenericDialect{},
	}
}

// NewExporterWithDialect 创建带方言的 SQL 导出器
func NewExporterWithDialect(dbType string) *Exporter {
	return &Exporter{
		dialect: GetDialect(dbType),
	}
}

// Export 导出表结构
func (e *Exporter) Export(tables []model.Table, options exporter.ExportOptions) error {
	// 根据数据库类型选择方言
	if options.DbType != "" {
		e.dialect = GetDialect(options.DbType)
	}

	if options.SplitFiles {
		return e.exportSplitFiles(tables, options)
	}
	return e.exportSingleFile(tables, options)
}

// exportSingleFile 导出到单个文件
func (e *Exporter) exportSingleFile(tables []model.Table, options exporter.ExportOptions) error {
	outputPath := filepath.Join(options.OutputDir, options.FileName)
	if outputPath == "" || outputPath == options.OutputDir {
		outputPath = filepath.Join(options.OutputDir, "schema.sql")
	}

	// 检查输出路径是否为已存在的目录
	info, err := os.Stat(outputPath)
	if err == nil && info.IsDir() {
		outputPath = filepath.Join(outputPath, "schema.sql")
	}

	if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	file, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to create file: %w", err)
	}
	defer file.Close()

	// 写入文件头
	fmt.Fprintln(file, "-- ========================================================")
	fmt.Fprintln(file, "-- Database Schema DDL")
	fmt.Fprintln(file, "-- Generated by schema-export tool")
	fmt.Fprintln(file, "-- Dialect:", e.dialect.GetName())
	fmt.Fprintln(file, "-- ========================================================")
	fmt.Fprintln(file, "")
	fmt.Fprintf(file, "-- Total Tables: %d\n", len(tables))
	fmt.Fprintln(file, "")

	// 写入表清单
	fmt.Fprintln(file, "-- --------------------------------------------------------")
	fmt.Fprintln(file, "-- Table List")
	fmt.Fprintln(file, "-- --------------------------------------------------------")
	for i, table := range tables {
		if table.Comment != "" {
			fmt.Fprintf(file, "-- %d. %s - %s\n", i+1, table.Name, table.Comment)
		} else {
			fmt.Fprintf(file, "-- %d. %s\n", i+1, table.Name)
		}
	}
	fmt.Fprintln(file, "")

	// 写入每个表的 DDL
	for _, table := range tables {
		if err := e.writeTableDDL(file, &table); err != nil {
			return err
		}
		fmt.Fprintln(file, "")
	}

	return nil
}

// exportSplitFiles 分文件导出
func (e *Exporter) exportSplitFiles(tables []model.Table, options exporter.ExportOptions) error {
	sqlDir := filepath.Join(options.OutputDir, "sql")
	if err := os.MkdirAll(sqlDir, 0755); err != nil {
		return fmt.Errorf("failed to create sql directory: %w", err)
	}

	for _, table := range tables {
		outputPath := filepath.Join(sqlDir, table.Name+".sql")
		file, err := os.Create(outputPath)
		if err != nil {
			return fmt.Errorf("failed to create file %s: %w", outputPath, err)
		}

		// 写入单个文件的头部
		fmt.Fprintf(file, "-- ========================================================\n")
		fmt.Fprintf(file, "-- Table: %s\n", table.Name)
		if table.Comment != "" {
			fmt.Fprintf(file, "-- Description: %s\n", table.Comment)
		}
		fmt.Fprintf(file, "-- Dialect: %s\n", e.dialect.GetName())
		fmt.Fprintf(file, "-- ========================================================\n")
		fmt.Fprintln(file, "")

		if err := e.writeTableDDL(file, &table); err != nil {
			file.Close()
			return err
		}
		file.Close()
	}

	return nil
}

// writeTableDDL 写入单个表的 DDL
func (e *Exporter) writeTableDDL(file *os.File, table *model.Table) error {
	// 写入表头注释
	fmt.Fprintf(file, "-- --------------------------------------------------------\n")
	fmt.Fprintf(file, "-- Table: %s\n", table.Name)
	fmt.Fprintln(file, "-- --------------------------------------------------------")
	if table.Comment != "" {
		fmt.Fprintf(file, "-- Description: %s\n", table.Comment)
	}
	fmt.Fprintf(file, "-- Type: %s\n", table.Type)
	fmt.Fprintf(file, "-- Columns: %d\n", len(table.Columns))
	fmt.Fprintf(file, "-- Indexes: %d\n", len(table.Indexes))
	fmt.Fprintf(file, "-- Foreign Keys: %d\n", len(table.ForeignKeys))
	fmt.Fprintf(file, "-- Check Constraints: %d\n", len(table.CheckConstraints))
	fmt.Fprintln(file, "")

	// 写入 CREATE TABLE 语句
	fmt.Fprintf(file, "CREATE TABLE %s (\n", e.dialect.QuoteIdentifier(table.Name))

	// 写入字段定义
	for i, col := range table.Columns {
		colDef := e.dialect.GetColumnDefinition(&col)
		if i < len(table.Columns)-1 || len(table.CheckConstraints) > 0 {
			fmt.Fprintf(file, "    %s,\n", colDef)
		} else {
			fmt.Fprintf(file, "    %s\n", colDef)
		}
	}

	// 写入 CHECK 约束
	for i, cc := range table.CheckConstraints {
		if i < len(table.CheckConstraints)-1 {
			fmt.Fprintf(file, "    %s,\n", e.dialect.GetCheckConstraint(&cc))
		} else {
			fmt.Fprintf(file, "    %s\n", e.dialect.GetCheckConstraint(&cc))
		}
	}

	fmt.Fprintln(file, ");")

	// 写入表注释
	if table.Comment != "" {
		commentSQL := e.dialect.GetTableCommentSQL(table.Name, table.Comment)
		if commentSQL != "" {
			fmt.Fprintln(file, "")
			fmt.Fprintln(file, commentSQL)
		}
	}

	// 写入字段注释（如果不支持内联注释）
	if !e.dialect.SupportsInlineComment() {
		for _, col := range table.Columns {
			if col.Comment != "" {
				commentSQL := e.dialect.GetColumnCommentSQL(table.Name, &col)
				if commentSQL != "" {
					fmt.Fprintln(file, commentSQL)
				}
			}
		}
	}

	// 写入索引
	if len(table.Indexes) > 0 {
		fmt.Fprintln(file, "")
		fmt.Fprintln(file, "-- --------------------------------------------------------")
		fmt.Fprintf(file, "-- Indexes for %s\n", table.Name)
		fmt.Fprintln(file, "-- --------------------------------------------------------")
		for _, idx := range table.Indexes {
			if idx.IsPrimary {
				fmt.Fprintf(file, "-- Primary Key: %s on (%s)\n", idx.Name, strings.Join(idx.Columns, ", "))
			} else {
				uniqueStr := ""
				if idx.IsUnique {
					uniqueStr = "UNIQUE "
				}
				fmt.Fprintf(file, "CREATE %sINDEX %s ON %s (%s);\n",
					uniqueStr,
					e.dialect.QuoteIdentifier(idx.Name),
					e.dialect.QuoteIdentifier(table.Name),
					e.quoteColumns(idx.Columns))
			}
		}
	}

	// 写入外键
	if len(table.ForeignKeys) > 0 {
		fmt.Fprintln(file, "")
		fmt.Fprintln(file, "-- --------------------------------------------------------")
		fmt.Fprintf(file, "-- Foreign Keys for %s\n", table.Name)
		fmt.Fprintln(file, "-- --------------------------------------------------------")
		for _, fk := range table.ForeignKeys {
			fmt.Fprintf(file, "-- Relationship: %s.%s -> %s.%s\n",
				table.Name, fk.Column, fk.RefTable, fk.RefColumn)
			fmt.Fprintf(file, "ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s(%s)",
				e.dialect.QuoteIdentifier(table.Name),
				e.dialect.QuoteIdentifier(fk.Name),
				e.dialect.QuoteIdentifier(fk.Column),
				e.dialect.QuoteIdentifier(fk.RefTable),
				e.dialect.QuoteIdentifier(fk.RefColumn))
			if fk.OnDelete != "" {
				fmt.Fprintf(file, " ON DELETE %s", fk.OnDelete)
			}
			fmt.Fprintln(file, ";")
		}
	}

	return nil
}

// quoteColumns 引用多个字段名
func (e *Exporter) quoteColumns(columns []string) string {
	quoted := make([]string, len(columns))
	for i, col := range columns {
		quoted[i] = e.dialect.QuoteIdentifier(col)
	}
	return strings.Join(quoted, ", ")
}

// GetName 获取导出器名称
func (e *Exporter) GetName() string {
	return "sql"
}

// GetExtension 获取文件扩展名
func (e *Exporter) GetExtension() string {
	return ".sql"
}

// Factory SQL Exporter 工厂
type Factory struct{}

// Create 创建 Exporter 实例
func (f *Factory) Create() (exporter.Exporter, error) {
	return NewExporter(), nil
}

// GetType 获取导出器类型
func (f *Factory) GetType() string {
	return "sql"
}

func init() {
	exporter.Register("sql", &Factory{})
}
